locale = "zh-Hans"
label = "简体中文"
direction = "ltr"
weight = 1
contentDir = "content"

title = "JasperSao的博客"

[params.author]
name = "JasperSao"
image = "img/author.webp"
headline = "我走了很远才来到你面前"
bio = "我走了很远才来到你面前"
links = [
    { email = "mailto:shijingyuan061010@gmail.com" },
    { github = "https://github.com/JasperStonnne" },
    { linuxdo = "https://linux.do/u/jaspersao/summary" }
]
